services:
  db:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=testdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    image: build-image
    command: ./mvnw verify -DskipTests
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db-data: